### PR TITLE
feat: add serializer and deserializer for GUID

### PR DESCRIPTION
**Pull request by somehowchris**
- added serde serialize and deserialize via feature flag
- Updated dependencies
- Ran tests, all were ok
- Build via `cargo build —all-features` was ok

Cheers 🍻 

 @kurtlawrence

### CODE REVIEW

**Comment by somehowchris** [comment]
@kurtlawrence lovely to see that the repository hasn't been abondend, mind publishing it on crates.io again?

**Comment by kurtlawrence** [comment]
Hi @somehowchris, I've just published `0.2`.

**Comment by kurtlawrence** [comment]
@somehowchris, would you like to become part-owner of this repository?

**Comment by somehowchris** [comment]
Well there‘s not much going on as it seems, but if you do not plan to maintain it yourself then sure, would love to help out

**Pull request merged**
